language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.3
          dist: trusty
          sudo: false
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: pypy
          dist: trusty
          sudo: false
        - python: pypy3
          dist: trusty
          sudo: false
       
install:
  - pip install -e ".[test]"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then
        py.test --doctest-modules --doctest-glob="*.rst" --ignore setup.py;
    else
        isort --recursive --diff intervals tests && isort --recursive --check-only intervals tests
        flake8 intervals tests
        py.test;
    fi
